jobs:
- job: Ubuntu
  strategy:
    matrix:
      aarch64:
        ARCH: ARM64
  pool: 
    name: default
    demands: agent.name -equals aarch64
  steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
    displayName: 'Install cargo'
  - script: |
      export PATH=$PATH:$HOME/.cargo/bin
      cargo build --lib
    displayName: 'Build library'
  - script: |
      export PATH=$PATH:$HOME/.cargo/bin
      RUST_BACKTRACE=full cargo test --lib
    displayName: 'Library tests'
  - script: |
      export PATH=$PATH:$HOME/.cargo/bin
      RUST_BACKTRACE=full cargo test --lib -- --ignored --test-threads=1
    displayName: 'Library interop tests'
  - script: |
      export PATH=$PATH:$HOME/.cargo/bin
      cargo build --bin wireguard-cf
    displayName: 'Build binary'
  - script: |
      export PATH=$PATH:$HOME/.cargo/bin
      RUST_BACKTRACE=full cargo test --bin wireguard-cf
    displayName: 'Binary tests'