[Interface]
Address = 10.13.13.1/24
ListenPort = 443
MTU = 1280
PrivateKey = $(cat /config/server/privatekey-server)
PostUp = iptables -t nat -A PREROUTING -i %i -p tcp --dport 443 -j REDIRECT --to-port 3001
PostUp = iptables -t nat -A PREROUTING -i %i -p tcp --dport 80 -j REDIRECT --to-port 3001
PostUp = iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostUp = iptables -A FORWARD -i %i -j ACCEPT
PostUp = iptables -A FORWARD -o %i -j ACCEPT
PostDown = iptables -t nat -D PREROUTING -i %i -p tcp --dport 443 -j REDIRECT --to-port 3001
PostDown = iptables -t nat -D PREROUTING -i %i -p tcp --dport 80 -j REDIRECT --to-port 3001
PostDown = iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT
PostDown = iptables -D FORWARD -o %i -j ACCEPT
